name: todo_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_slidable: ^1.2.0
  animated_splash_screen: ^1.3.0
  double_back_to_close_app: ^2.1.0
  fluttertoast: ^8.2.4
  google_fonts: ^4.0.4
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - images/